#!/bin/sh

# BMS GCOV coverage report
# Compatible with /bin/sh and GCC gcov.
# Usage:
#   sh bms_coverage.sh [PROJECT_DIR]
#
# The script reads existing .gcno/.gcda files. It does not modify source code.

set -u

PROJECT_DIR="${1:-.}"

if [ ! -d "$PROJECT_DIR" ]; then
    echo "ERROR: Project directory not found: $PROJECT_DIR"
    exit 1
fi

PROJECT_DIR=$(cd "$PROJECT_DIR" 2>/dev/null && pwd)

if ! command -v gcov >/dev/null 2>&1; then
    echo "ERROR: gcov is not installed or not in PATH."
    exit 1
fi

echo "============================================================"
echo "                 BMS CODE COVERAGE"
echo "============================================================"
echo "Project : $PROJECT_DIR"
echo "gcov    : $(gcov --version | head -n 1)"
echo

TMP_DIR="${TMPDIR:-/tmp}/bms_gcov_$$"
mkdir -p "$TMP_DIR" || exit 1
trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM

# Counters
LINE_COV=0
LINE_TOTAL=0
FUNC_COV=0
FUNC_TOTAL=0
BRANCH_COV=0
BRANCH_TOTAL=0
DATA_FILES=0

# Per-file report
REPORT="$TMP_DIR/report.txt"
: > "$REPORT"

# Find .gcno files.  Avoid bash-only mapfile/process-substitution syntax.
find "$PROJECT_DIR" -type f -name '*.gcno' -print > "$TMP_DIR/gcno.list"

if [ ! -s "$TMP_DIR/gcno.list" ]; then
    echo "ERROR: No .gcno files found under $PROJECT_DIR"
    exit 1
fi

while IFS= read -r GCNO; do
    [ -f "$GCNO" ] || continue

    DIR=$(dirname "$GCNO")
    BASE=$(basename "$GCNO" .gcno)
    GCDA="$DIR/$BASE.gcda"

    # gcov needs the .gcda data for executed coverage.  Skip files with
    # no matching data rather than treating them as executed/zero coverage.
    if [ ! -f "$GCDA" ]; then
        continue
    fi

    DATA_FILES=$((DATA_FILES + 1))

    # Run gcov in the directory containing the coverage pair.
    # -b: branch information
    # -f: function information
    # -o: object/coverage directory
    OUT="$TMP_DIR/out_$DATA_FILES.txt"

    (
        cd "$DIR" || exit 1
        gcov -b -f -o "$DIR" "$BASE.gcno"
    ) > "$OUT" 2>&1

    # gcov can produce a report even with warnings.  Only continue if
    # it generated a source summary.
    if ! grep -qE 'File .+:' "$OUT"; then
        continue
    fi

    # Parse source summary generated by gcov.
    #
    # Lines:
    #   Lines executed:94.52% of 3157
    #   Functions executed:...
    #   Branches executed:98.49% of 1849
    #
    # Function count is obtained from gcov -f's individual function lines:
    #   94.44% of 18 lines executed in function 'foo'
    # Unexecuted functions are reported as:
    #   #####: ... lines ... in function 'foo'
    #
    # We count a function as covered when its gcov function execution
    # percentage is greater than 0.

    FILE_LINES_TOTAL=0
    FILE_LINES_COV=0
    FILE_BRANCH_TOTAL=0
    FILE_BRANCH_COV=0
    FILE_FUNC_TOTAL=0
    FILE_FUNC_COV=0

    # Parse "Lines executed:X% of Y".
    LINE_INFO=$(grep -m1 -E '^Lines executed:[0-9.]+% of [0-9]+' "$OUT" || true)
    if [ -n "$LINE_INFO" ]; then
        LINE_PCT=$(printf '%s\n' "$LINE_INFO" | sed -n 's/^Lines executed:\([0-9.]*\)% of \([0-9][0-9]*\).*/\1 \2/p')
        LINE_PCT_VAL=$(printf '%s' "$LINE_PCT" | awk '{print $1}')
        FILE_LINES_TOTAL=$(printf '%s' "$LINE_PCT" | awk '{print $2}')
        FILE_LINES_COV=$(awk -v p="$LINE_PCT_VAL" -v t="$FILE_LINES_TOTAL" 'BEGIN {printf "%.0f", (p*t/100)+0.000001}')
    fi

    # Parse "Branches executed:X% of Y".
    BRANCH_INFO=$(grep -m1 -E '^Branches executed:[0-9.]+% of [0-9]+' "$OUT" || true)
    if [ -n "$BRANCH_INFO" ]; then
        BRANCH_PCT=$(printf '%s\n' "$BRANCH_INFO" | sed -n 's/^Branches executed:\([0-9.]*\)% of \([0-9][0-9]*\).*/\1 \2/p')
        BRANCH_PCT_VAL=$(printf '%s' "$BRANCH_PCT" | awk '{print $1}')
        FILE_BRANCH_TOTAL=$(printf '%s' "$BRANCH_PCT" | awk '{print $2}')
        FILE_BRANCH_COV=$(awk -v p="$BRANCH_PCT_VAL" -v t="$FILE_BRANCH_TOTAL" 'BEGIN {printf "%.0f", (p*t/100)+0.000001}')
    fi

    # Parse function summary. GCC gcov prints one line per function when -f
    # is used. We intentionally parse the "in function" records instead of
    # relying on a version-specific "Functions executed" summary.
    #
    # Example:
    #   100.00% of 10 lines executed in function 'foo'
    #   0.00% of 10 lines executed in function 'bar'
    #
    # A function is considered covered when its function execution percentage
    # is greater than 0.
    while IFS= read -r FLINE; do
        FPCT=$(printf '%s\n' "$FLINE" | sed -n "s/^[[:space:]]*\([0-9][0-9.]*\)% of .* in function .*/\1/p")
        if [ -n "$FPCT" ]; then
            FILE_FUNC_TOTAL=$((FILE_FUNC_TOTAL + 1))
            IS_COVERED=$(awk -v p="$FPCT" 'BEGIN {if (p > 0) print 1; else print 0}')
            if [ "$IS_COVERED" -eq 1 ]; then
                FILE_FUNC_COV=$((FILE_FUNC_COV + 1))
            fi
        fi
    done < "$OUT"

    LINE_TOTAL=$((LINE_TOTAL + FILE_LINES_TOTAL))
    LINE_COV=$((LINE_COV + FILE_LINES_COV))
    BRANCH_TOTAL=$((BRANCH_TOTAL + FILE_BRANCH_TOTAL))
    BRANCH_COV=$((BRANCH_COV + FILE_BRANCH_COV))
    FUNC_TOTAL=$((FUNC_TOTAL + FILE_FUNC_TOTAL))
    FUNC_COV=$((FUNC_COV + FILE_FUNC_COV))

    # Save a concise per-file row.
    LINE_FILE_PCT=$(awk -v c="$FILE_LINES_COV" -v t="$FILE_LINES_TOTAL" 'BEGIN {if(t>0) printf "%.2f",100*c/t; else printf "0.00"}')
    FUNC_FILE_PCT=$(awk -v c="$FILE_FUNC_COV" -v t="$FILE_FUNC_TOTAL" 'BEGIN {if(t>0) printf "%.2f",100*c/t; else printf "0.00"}')
    BRANCH_FILE_PCT=$(awk -v c="$FILE_BRANCH_COV" -v t="$FILE_BRANCH_TOTAL" 'BEGIN {if(t>0) printf "%.2f",100*c/t; else printf "0.00"}')

    printf '%s|%s|%s|%s|%s|%s|%s\n' \
        "$(basename "$GCNO")" \
        "$LINE_FILE_PCT" "$FILE_LINES_COV" "$FILE_LINES_TOTAL" \
        "$FUNC_FILE_PCT" "$FILE_FUNC_COV" "$FILE_FUNC_TOTAL" \
        >> "$REPORT"

    # Store branch percentage separately because the report format is simple.
    printf '%s|%s|%s|%s\n' \
        "$(basename "$GCNO")" "$BRANCH_FILE_PCT" "$FILE_BRANCH_COV" "$FILE_BRANCH_TOTAL" \
        >> "$TMP_DIR/branches.report"

done < "$TMP_DIR/gcno.list"

# Calculate final percentages from totals, not by averaging file percentages.
LINE_PCT=$(awk -v c="$LINE_COV" -v t="$LINE_TOTAL" 'BEGIN {if(t>0) printf "%.2f",100*c/t; else printf "0.00"}')
FUNC_PCT=$(awk -v c="$FUNC_COV" -v t="$FUNC_TOTAL" 'BEGIN {if(t>0) printf "%.2f",100*c/t; else printf "0.00"}')
BRANCH_PCT=$(awk -v c="$BRANCH_COV" -v t="$BRANCH_TOTAL" 'BEGIN {if(t>0) printf "%.2f",100*c/t; else printf "0.00"}')

# Overall is an item-weighted coverage, not an average of percentages.
OVERALL_COV=$((LINE_COV + FUNC_COV + BRANCH_COV))
OVERALL_TOTAL=$((LINE_TOTAL + FUNC_TOTAL + BRANCH_TOTAL))
OVERALL_PCT=$(awk -v c="$OVERALL_COV" -v t="$OVERALL_TOTAL" 'BEGIN {if(t>0) printf "%.2f",100*c/t; else printf "0.00"}')

echo "Coverage data files : $DATA_FILES"
echo
echo "Line coverage       : $LINE_PCT% ($LINE_COV/$LINE_TOTAL)"
echo "Function coverage   : $FUNC_PCT% ($FUNC_COV/$FUNC_TOTAL)"
echo "Branch coverage     : $BRANCH_PCT% ($BRANCH_COV/$BRANCH_TOTAL)"
echo "Overall BMS coverage: $OVERALL_PCT% ($OVERALL_COV/$OVERALL_TOTAL)"
echo
echo "------------------------------------------------------------"
printf "%-42s %10s %10s %10s\n" "Coverage data file" "Lines" "Functions" "Branches"
echo "------------------------------------------------------------"

# Print per-file report, joining branch data by filename.
while IFS='|' read -r FILE LP LC LT FP FC FT EXTRA; do
    [ -n "$FILE" ] || continue
    BP=$(awk -F'|' -v f="$FILE" '$1==f {print $2; exit}' "$TMP_DIR/branches.report" 2>/dev/null)
    [ -n "$BP" ] || BP="0.00"
    printf "%-42s %9s%% %9s%% %9s%%\n" "$FILE" "$LP" "$FP" "$BP"
done < "$REPORT"

echo "------------------------------------------------------------"

SUMMARY="$PROJECT_DIR/coverage_percentage.txt"
{
    echo "BMS CODE COVERAGE SUMMARY"
    echo "Project: $PROJECT_DIR"
    echo
    echo "Line coverage       : $LINE_PCT% ($LINE_COV/$LINE_TOTAL)"
    echo "Function coverage   : $FUNC_PCT% ($FUNC_COV/$FUNC_TOTAL)"
    echo "Branch coverage     : $BRANCH_PCT% ($BRANCH_COV/$BRANCH_TOTAL)"
    echo "Overall BMS coverage: $OVERALL_PCT% ($OVERALL_COV/$OVERALL_TOTAL)"
    echo
    echo "Coverage data files : $DATA_FILES"
} > "$SUMMARY"

echo
echo "Summary saved to:"
echo "$SUMMARY"
